<?php
/**
 * @file
 * Module functions for viewsreference.
 */

use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\Xss;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function viewsreference_help($route_name, RouteMatchInterface $arg) {
  switch ($route_name) {
    case 'help.page.viewsreference':
      $output = file_get_contents(drupal_get_path('module', 'viewsreference') . '/README.md');
      $output = \Drupal::moduleHandler()->moduleExists('markdown')
        ? Xss::filterAdmin(\Drupal::moduleHandler()->invoke(
          'markdown',
          'filter',
          ['process', 0, -1, $output]
        ))
        : '<h3>viewsreference README</h3><pre>' . Html::escape($output) . '</pre>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function viewsreference_theme($existing, $type, $theme, $path) {
  return array(
    'viewsreference__view_title' => array(
      'template' => 'viewsreference--view-title',
      'render element' => 'variables',
    ),
  );
}

/**
 * Implements hook_preprocess_viewsreference__view_title().
 */
function viewsreference_preprocess_viewsreference__view_title(&$variables) {
  $variables['title'] = $variables['variables']['#title'];
}
